name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    IMAGE_NAME: 'flask-gallery'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Setup variables
      run: echo "GIT_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    -
      name: Build & push the Docker image
      run: |
          echo "Building Image name $IMAGE_NAME"
          docker build . --file Dockerfile --tag $IMAGE_NAME:$GIT_SHA_SHORT
          docker push $IMAGE_NAME:$GIT_SHA_SHORT