name: Docker Image CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: 'sd-webui-containers-auto1111'
  ORIGINAL_IMAGE: 'ffxvs/sd-webui-containers:auto1111-latest' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup variables
      run: |
        echo "GIT_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Image
      run: docker pull ${{ env.ORIGINAL_IMAGE }}

    - name: Tag the pulled image for push
      run: |
        docker tag ${{ env.ORIGINAL_IMAGE }} ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.GIT_SHA_SHORT }}
        docker tag ${{ env.ORIGINAL_IMAGE }} ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.GIT_SHA_SHORT }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
